#!/bin/bash

# -------------------------------------------------------------
# Capture a sequence of image pairs with varying exposure times
# -------------------------------------------------------------

DEF_TAG="flat"
DEF_GAIN=1
DEF_EXPOSURE_PLAN="linear"
DEF_WAVL_START=380
DEF_WAVL_END=1000
DEF_WAVWL_STEP=5
DEF_EXPTIME=800000

read -p "Start Wavelength (nm) [$DEF_WAVL_START]: " wavel_start
read -p "End   Wavelength (nm) [$DEF_WAVL_END]: " wavel_end
read -p "Exposure time (us) [$DEF_EXPTIME]: " t


analog_gain=${analog_gain:-$DEF_GAIN}
tag=${tag:-$DEF_TAG}
wavl_step=${wavl_step:-$DEF_WAVWL_STEP}
wavel_start=${wavel_start:-$DEF_WAVL_START}
wavel_end=${wavel_end:-$DEF_WAVL_END}
tag=${t:-$DEF_EXPTIME}
i=001

for (( wvl=wavel_start; wvl<=wavel_end; ))
do
	wv=$(printf '%04d' $wvl)
	g=$(printf "%02d" $analog_gain)
	image=${tag}_${wv}nm_g${g}_${i}_${t}.jpg
	echo "raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image}"
	raspistill --raw --shutter ${t} --timeout 100 -drc off --nopreview -ex off -awb off --analoggain ${analog_gain} --digitalgain 1 --output ${image} || exit 255
	wvl=$((wvl+wavl_step))
	read -p "Ready for the next wavelength ($wvl nm)? [y]: " answer
	if [[ "$answer" != "y" ]]
	then
		break
	fi
done  
